language: python
group: travis_latest

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    name: Lint
    install: pip install -e .[lint]
    script:
    - flake8
    - mypy .

install: pip install -e .[tests]

script: pytest -r a -v
